database:
  mongo:
    url: mongodb://127.0.0.1:27017/dolphjs
    options:
  # mysql:
  #   host: localhost
  #   database: dolph
  #   user: root
  #   pass:
middlewares:
  cors:
    activate: true
    origin: ''
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowedHeaders:
routing:
  base: '/v1'
port: 3030
jsonLimit: 20mb
# env: production
